### PR TITLE
Android 14 related fixes

### LINKED ISSUE #258: App doesn't stop recordings when device is powered off resulting in corrupted files
### Steps to reproduce

Start a screen recording and then turn off your device.

### Expected behavior

It should end the recording so it saves properly.

### Actual behavior

It corrupts the mp4 video file and won't play.

### Record You version

7.3

### Android version

13

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by pvagner**
* Use FOREGROUND_SERVICE_MICROPHONE permission
* Similarly how ScreenRecorderService overrides fgServiceType property to FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION make both AudioRecorderService and LosslessRecorderService inline with this on android 14 and newer by overriding its fgServiceType to FOREGROUND_SERVICE_TYPE_MICROPHONE.
* RecorderService: When registering receivers use the RECEIVER_EXPORTED flag to avoid security exceptions on Android 14
* ScreenRecorderService: added onStop callback to the MediaProjection. It may possibly fix #258.

### CODE REVIEW

**Comment by pvagner** [comment]
Quick tiles can't start foreground services on Android 14 so merging this is not usefull yet.
https://issuetracker.google.com/issues/299506164?pli=1

File: app/src/main/java/com/bnyro/recorder/services/RecorderService.kt [hunk 1]
```diff
@@ -91,16 +91,28 @@ abstract class RecorderService : LifecycleService() {
...
+                bluetoothReceiver,
+                IntentFilter(AudioManager.ACTION_SCO_AUDIO_STATE_UPDATED),
+                RECEIVER_EXPORTED
+            )
+        } else {
+            registerReceiver(
+                bluetoothReceiver,
+                IntentFilter(AudioManager.ACTION_SCO_AUDIO_STATE_UPDATED)
+            )
+        }
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/recorder/services/RecorderService.kt:105]: We can use [ContextCompat#registerReceiver](https://developer.android.com/reference/androidx/core/content/ContextCompat#registerReceiver(android.content.Context,android.content.BroadcastReceiver,android.content.IntentFilter,int) instead).

File: app/src/main/java/com/bnyro/recorder/services/RecorderService.kt [hunk 2]
```diff
@@ -91,16 +91,28 @@ abstract class RecorderService : LifecycleService() {
...
 
         runCatching {
             unregisterReceiver(recorderReceiver)
         }
-        registerReceiver(recorderReceiver, IntentFilter(RECORDER_INTENT_ACTION))
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
+            registerReceiver(recorderReceiver, IntentFilter(RECORDER_INTENT_ACTION), RECEIVER_EXPORTED)
+        } else {
+            registerReceiver(recorderReceiver, IntentFilter(RECORDER_INTENT_ACTION))
+        }
```
Comment (Bnyro) [inline app/src/main/java/com/bnyro/recorder/services/RecorderService.kt:115]: Same as above

**Review by Bnyro — APPROVED** [review]
Thanks :+1:
